[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.69"
js-sys = "0.3.46"
wasm-bindgen-futures = "0.4.19"
wee_alloc = { version = "0.4.5" }
lazy_static = "1.4.0"
codespan-reporting = { path = "lib/codespan-reporting" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed="5.6.0"
infer = { version = "0.2", default-features = false }
strum = { version = "0.20", features = ["derive"] }
peg = "0.6.3"

[profile.release]
opt-level = "s"
