[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"

[dependencies]
codespan-reporting = { path = "codespan-reporting" }
tungstenite = { path = "tungstenite-rs" }
