[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"


[dependencies]
codespan-reporting = { path = "codespan-reporting" }
lazy_static = "1.4.0"

[dependencies.rust-embed]
version = "5.6.0"
features = ["debug-embed"]
