[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5" }
lazy_static = "1.4.0"
codespan-reporting = { path = "codespan-reporting" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itoa = "0.4.6"
rust-embed="5.6.0"
infer = { version = "0.2", default-features = false }
strum = { version = "0.20", features = ["derive"] }
peg = "0.6.3"

[profile.release]
opt-level = "s"

