[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"

[dependencies]
codespan-reporting = { path = "codespan-reporting" }
embedded-websocket = { path = "embedded-websocket" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itoa = "0.4.6"
rust-embed="5.6.0"
infer = { version = "0.2", default-features = false }
strum = "0.19"
strum_macros = "0.19"
# tokio = "0.1.13"
# smol = "1.0.1"
