[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
codespan-reporting = { path = "codespan-reporting" }
embedded-websocket = { path = "embedded-websocket" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itoa = "0.4.6"
rust-embed="5.6.0"
infer = { version = "0.2", default-features = false }
strum = { version = "0.20", features = ["derive"] }
smol = "1.2.5"
tokio = { version = "0.3.6", features = ["rt", "rt-multi-thread"] }
rand = "0.8.0"
# llvm-ir = { version = "0.7.4", features = ["llvm-10"] }
