version: '3.3'

services:

  reverse-proxy:
    # The official v2.1 Traefik docker image
    image: traefik:v2.1
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"

      # You need to actively say traefik.enable=true
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=al5932@nyu.edu"
      - "--certificatesresolvers.mytlschallenge.acme.storage=letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  tci:
    image: a1liu/tci:latest
    labels:
      - "traefik.enable=true"

        # HTTPS
      - "traefik.http.routers.tci-https.rule=Host(`tci.a1liu.com`)"
      - "traefik.http.routers.tci-https.service=tci-https"
      - "traefik.http.routers.tci-https.entrypoints=websecure"
      - "traefik.http.services.tci-https.loadbalancer.server.port=3000"
      - "traefik.http.routers.tci-https.tls.certresolver=mytlschallenge"

        #HTTP
      - "traefik.http.routers.tci-http.rule=Host(`tci.a1liu.com`, `localhost`)"
      - "traefik.http.routers.tci-http.service=tci-http"
      - "traefik.http.routers.tci-http.entrypoints=web"
      - "traefik.http.services.tci-http.loadbalancer.server.port=3000"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: unless-stopped

